name: Build OpenClaw Docker Image

on:
  workflow_dispatch:    

      
env:
  # GitHub Container Registry
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE_NAME: ${{ github.repository }}/linux_latest  

jobs:
  build-openclaw:
    uses: ./.github/workflows/base-workflow.yml 
    with:
      app-name: 'openclaw'
      docker-file: './docker/Dockerfile'  
    permissions:
      contents: read
      packages: write

